# Generated by Django 5.1.1 on 2024-09-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoliq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residue',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
