# Generated by Django 5.1.1 on 2024-09-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoliq', '0002_alter_residue_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
