version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
services:
  postgres:
    image: postgres:13
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
      PGDATA: /data/postgres

  api: 
    build: ./api
    image: api
    depends_on:
      - postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  #react:
  #  build: ./resoliq_ui
  #  image: ui
  #  ports:
  #    - "4200:80"
  #  depends_on:
  #    - api 
  #    - postgres
